spring.application.name=appetize

# Configuracion de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${DATABASE_NAME}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${DDL-AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
security.jwt.key=${JWT_KEY}
security.jwt.user=${JWT_USER}
