spring.application.name=appetize

#Configuración de la Base de Datos
spring.datasource.url=jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/${DATABASE_NAME}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.diver=com.mysql.cj.jdbc.Driver

#Configuración Jpa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
